[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "effin cookbook"
authors = [{name = "Christopher P Yarger", email = "cpyarger@gmail.com"}]
dynamic = ["version", "description"]
